add customer reviews
chertoha/ice-cream-project-group-28 pull request #3
Opened 2022-07-14 16:56 UTC by JulyKapuza

1. Підключила бібліотеку по слайдеру
2. внесла основні стилі без картинок

2022-07-14 21:29 UTC, chertoha requested changes

2022-07-14 21:29 UTC, chertoha commented on src/partials/reviews.html
> +<article class="reviews">
думаю нужно сделать section , в нем контейнер, а в нем уже article.
<section class="section">  
Семантически может быть такое что в данной секции статья будет только частью секции. Например дизайнер захочет добавить видимый заголовок

2022-07-15 06:18 UTC, JulyKapuza commented on src/partials/reviews.html
> +<article class="reviews">
виправила, можем це обговорити на meeting

2022-07-15 06:19 UTC, JulyKapuza commented on src/partials/reviews.html
> +          <h1 class="visually-hidden">Reviews</h1>
зробила hidden, хоча мені ментор казав через клас, цікаво, яка різниця, що коли застосовувати

2022-07-15 06:20 UTC, JulyKapuza commented on src/partials/reviews.html
> +
поставила h2, на сайті по специфікації є такі приклади, тому тут погоджуюсь

2022-07-15 06:45 UTC, chertoha approved these changes

2022-07-15 06:45 UTC, merged